#!/usr/bin/env node
/**
 * AUTO-GENERATED by src/kernel/runtime/agent-scripts/bundle-sparrow-state.mjs — do not edit by hand.
 * Source: src/kernel/runtime/agent-scripts/sparrow-state.ts (+ src/kernel/runtime/project-state.ts).
 * Re-run: npm run sync-schema
 */
// src/kernel/runtime/project-state-types.ts
var DEFAULT_PROJECT_STATE = {
  "active-change": { changeId: null },
  "development-mode": "tbd",
  pipeline: null
};
var MODES = /* @__PURE__ */ new Set(["tbd", "greenfield", "brownfield", "iteration"]);
var STEPS = /* @__PURE__ */ new Set([
  "requirement",
  "architecture",
  "design",
  "model",
  "plan",
  "apply",
  "verify",
  "archive"
]);
var STATUSES = /* @__PURE__ */ new Set(["ongoing", "done"]);
function normalizeProjectState(raw) {
  const src = raw && typeof raw === "object" ? raw : {};
  const active = src["active-change"] && typeof src["active-change"] === "object" ? src["active-change"] : {};
  const changeId = typeof active.changeId === "string" && active.changeId.length > 0 ? active.changeId : null;
  const mode = MODES.has(src["development-mode"]) ? src["development-mode"] : "tbd";
  let pipeline = null;
  if (mode !== "tbd" && src.pipeline && typeof src.pipeline === "object") {
    const p = src.pipeline;
    const step = STEPS.has(p["current-step"]) ? p["current-step"] : "requirement";
    const status = STATUSES.has(p.status) ? p.status : "ongoing";
    const contexts = {};
    if (p.contexts && typeof p.contexts === "object") {
      for (const [slug, value] of Object.entries(p.contexts)) {
        if (!value || typeof value !== "object") continue;
        const c = value;
        if (!STEPS.has(c["current-step"]) || !STATUSES.has(c.status)) {
          continue;
        }
        contexts[slug] = {
          "current-step": c["current-step"],
          status: c.status
        };
      }
    }
    pipeline = { "current-step": step, status, contexts };
  }
  return {
    "active-change": { changeId },
    "development-mode": mode,
    pipeline: mode === "tbd" ? null : pipeline
  };
}

// src/kernel/runtime/project-state-io.ts
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

// src/kernel/runtime/spec-paths.ts
var SPARROW_DOCS = "docs/sparrow";
var SPARROW_DIR = ".sparrow";
var CONFIG_FILE = `${SPARROW_DIR}/sparrow-config.json`;
var LEGACY_CONFIG_FILE = `${SPARROW_DIR}/sparrow.json`;
var STATE_FILE = `${SPARROW_DIR}/sparrow-state.json`;
var LEGACY_ACTIVE_CHANGE_FILE = `${SPARROW_DIR}/active-change.json`;
var MASTER_ROOT = `${SPARROW_DOCS}/master`;
var CHANGE_ROOT = `${SPARROW_DOCS}/change`;
var CHANGE_CURRENT = `${CHANGE_ROOT}/current`;
var CHANGE_ARCHIVE = `${CHANGE_ROOT}/archive`;
var MASTER_PROJECT_MD = `${MASTER_ROOT}/project.md`;
var MASTER_REQUIREMENT_HISTORY = `${MASTER_ROOT}/requirement/revision-history.md`;
var MASTER_DESIGN_HISTORY = `${MASTER_ROOT}/design/revision-history.md`;
var MASTER_BC_HISTORY = `${MASTER_ROOT}/architecture/bc-revision-history.md`;
var LEGACY_CHANGES_ROOT = `${SPARROW_DOCS}/changes`;

// src/kernel/runtime/project-state-io.ts
function stateAbsPath(projectRoot) {
  return join(projectRoot, STATE_FILE);
}
function loadProjectState(projectRoot) {
  const path = stateAbsPath(projectRoot);
  if (!existsSync(path)) {
    return { ...DEFAULT_PROJECT_STATE, "active-change": { changeId: null }, pipeline: null };
  }
  try {
    return normalizeProjectState(JSON.parse(readFileSync(path, "utf-8")));
  } catch {
    return { ...DEFAULT_PROJECT_STATE };
  }
}
function saveProjectState(projectRoot, state) {
  const normalized = normalizeProjectState(state);
  const dest = stateAbsPath(projectRoot);
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, JSON.stringify(normalized, null, 2) + "\n", "utf-8");
  return dest;
}

// src/kernel/runtime/development-mode.ts
import { existsSync as existsSync2, readdirSync as readdirSync2, statSync } from "node:fs";
import { extname, join as join2 } from "node:path";
var IGNORE_DIRS = /* @__PURE__ */ new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  "coverage",
  ".sparrow",
  ".cursor",
  ".claude",
  ".codex",
  ".opencode",
  ".qoder",
  ".trae",
  ".pi",
  ".kiro",
  "vendor",
  ".github",
  "bin"
]);
var SOURCE_EXT = /* @__PURE__ */ new Set([
  ".ts",
  ".tsx",
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".py",
  ".go",
  ".java",
  ".kt",
  ".cs",
  ".rb",
  ".rs",
  ".php",
  ".swift",
  ".c",
  ".cc",
  ".cpp",
  ".h",
  ".hpp",
  ".m",
  ".mm",
  ".scala",
  ".vue",
  ".svelte"
]);
function dirHasFiles(dir) {
  if (!existsSync2(dir) || !statSync(dir).isDirectory()) return false;
  for (const name of readdirSync2(dir)) {
    const full = join2(dir, name);
    if (statSync(full).isDirectory()) {
      if (dirHasFiles(full)) return true;
    } else {
      return true;
    }
  }
  return false;
}
function hasSourceFiles(projectRoot) {
  const skipAbs = join2(projectRoot, SPARROW_DOCS);
  const walk = (dir) => {
    if (!existsSync2(dir) || !statSync(dir).isDirectory()) return false;
    for (const name of readdirSync2(dir)) {
      if (IGNORE_DIRS.has(name)) continue;
      const full = join2(dir, name);
      if (full === skipAbs || full.startsWith(skipAbs + "/") || full.startsWith(skipAbs + "\\")) continue;
      const st = statSync(full);
      if (st.isDirectory()) {
        if (walk(full)) return true;
      } else if (SOURCE_EXT.has(extname(name).toLowerCase())) {
        return true;
      }
    }
    return false;
  };
  return walk(projectRoot);
}
function detectDevelopmentMode(projectRoot) {
  const reasons = [];
  const currentHas = dirHasFiles(join2(projectRoot, CHANGE_CURRENT));
  const archiveHas = dirHasFiles(join2(projectRoot, CHANGE_ARCHIVE));
  const masterHas = dirHasFiles(join2(projectRoot, MASTER_ROOT));
  if (currentHas) reasons.push("change/current has documents");
  if (archiveHas) reasons.push("change/archive has documents");
  if (masterHas) reasons.push("master has documents");
  if (currentHas || archiveHas || masterHas) {
    return { mode: "iteration", reasons };
  }
  if (hasSourceFiles(projectRoot)) {
    reasons.push("archive and change are empty; source files found");
    return { mode: "brownfield", reasons };
  }
  reasons.push("archive and change are empty; no source files found");
  return { mode: "greenfield", reasons };
}

// src/kernel/runtime/archive-readiness.ts
import { existsSync as existsSync3, readdirSync as readdirSync3, statSync as statSync2 } from "node:fs";
import { join as join3 } from "node:path";
function listDesignSlugs(projectRoot, changeId) {
  const dir = join3(projectRoot, CHANGE_CURRENT, changeId, "design");
  if (!existsSync3(dir) || !statSync2(dir).isDirectory()) return [];
  return readdirSync3(dir).filter((name) => statSync2(join3(dir, name)).isDirectory()).sort();
}
function isSlugArchiveReady(ctx) {
  return ctx?.["current-step"] === "verify" && ctx?.status === "done";
}
function checkArchiveReadiness(projectRoot, changeId) {
  const state = loadProjectState(projectRoot);
  const id = changeId ?? state["active-change"].changeId;
  const contexts = state.pipeline?.contexts ?? {};
  const designSlugs = id ? listDesignSlugs(projectRoot, id) : [];
  const slugSet = /* @__PURE__ */ new Set([...Object.keys(contexts), ...designSlugs]);
  const ready = [];
  const incomplete = [];
  for (const slug of [...slugSet].sort()) {
    const ctx = contexts[slug];
    if (isSlugArchiveReady(ctx)) {
      ready.push({
        slug,
        "current-step": ctx["current-step"],
        status: ctx.status,
        ready: true,
        reason: "verify done"
      });
    } else {
      const step = ctx?.["current-step"] ?? null;
      const status = ctx?.status ?? null;
      let reason = "missing pipeline context";
      if (ctx) {
        reason = step === "verify" && status !== "done" ? "verify not done" : `at ${step}/${status}; need verify/done`;
      }
      incomplete.push({
        slug,
        "current-step": step,
        status,
        ready: false,
        reason
      });
    }
  }
  return {
    changeId: id,
    pipelineStep: state.pipeline?.["current-step"] ?? null,
    pipelineStatus: state.pipeline?.status ?? null,
    ready,
    incomplete,
    allComplete: incomplete.length === 0 && ready.length > 0,
    canPartialArchive: ready.length > 0
  };
}
function prunePipelineContexts(state, slugs) {
  if (!state.pipeline) return normalizeProjectState(state);
  const remove = new Set(slugs);
  const contexts = { ...state.pipeline.contexts };
  for (const slug of remove) {
    delete contexts[slug];
  }
  return normalizeProjectState({
    ...state,
    pipeline: {
      ...state.pipeline,
      contexts
    }
  });
}
function applyPruneContexts(projectRoot, slugs) {
  const next = prunePipelineContexts(loadProjectState(projectRoot), slugs);
  saveProjectState(projectRoot, next);
  return next;
}

// src/kernel/runtime/project-state.ts
function applyChangeId(state, changeId) {
  return normalizeProjectState({
    ...state,
    "active-change": { changeId }
  });
}
function applyDevelopmentMode(state, mode) {
  const next = { ...state, "development-mode": mode };
  if (mode === "tbd" || mode === "brownfield") {
    next.pipeline = null;
  }
  return normalizeProjectState(next);
}
function applyPipelineStep(state, step, status) {
  if (state["development-mode"] === "tbd") {
    throw new Error("Cannot set pipeline while development-mode is tbd");
  }
  const pipeline = state.pipeline ?? {
    "current-step": step,
    status,
    contexts: {}
  };
  pipeline["current-step"] = step;
  pipeline.status = status;
  return normalizeProjectState({ ...state, pipeline });
}
function applyPipelineContext(state, slug, step, status) {
  if (state["development-mode"] === "tbd") {
    throw new Error("Cannot set pipeline while development-mode is tbd");
  }
  const pipeline = state.pipeline ?? {
    "current-step": step,
    status,
    contexts: {}
  };
  pipeline["current-step"] = step;
  pipeline.status = status;
  pipeline.contexts = { ...pipeline.contexts, [slug]: { "current-step": step, status } };
  return normalizeProjectState({ ...state, pipeline });
}
function applyArchiveComplete(state) {
  const mode = state["development-mode"] === "greenfield" ? "iteration" : state["development-mode"];
  return normalizeProjectState({
    "active-change": { changeId: null },
    "development-mode": mode === "tbd" ? "iteration" : mode,
    pipeline: null
  });
}

// src/kernel/runtime/agent-scripts/sparrow-state.ts
var MODES2 = /* @__PURE__ */ new Set(["tbd", "greenfield", "brownfield", "iteration"]);
var STEPS2 = /* @__PURE__ */ new Set([
  "requirement",
  "architecture",
  "design",
  "model",
  "plan",
  "apply",
  "verify",
  "archive"
]);
var STATUSES2 = /* @__PURE__ */ new Set(["ongoing", "done"]);
function failUsage() {
  console.error("Usage:");
  console.error("  node scripts/sparrow-state.mjs show");
  console.error("  node scripts/sparrow-state.mjs detect-mode");
  console.error("  node scripts/sparrow-state.mjs set-mode <tbd|greenfield|brownfield|iteration>");
  console.error("  node scripts/sparrow-state.mjs set-change <id|null>");
  console.error("  node scripts/sparrow-state.mjs set-step <step> <ongoing|done>");
  console.error("  node scripts/sparrow-state.mjs set-context <slug> <step> <ongoing|done>");
  console.error("  node scripts/sparrow-state.mjs check-archive [change-id]");
  console.error("  node scripts/sparrow-state.mjs prune-contexts <slug> [slug...]");
  console.error("  node scripts/sparrow-state.mjs archive-done");
  process.exit(2);
}
function printJson(value) {
  process.stdout.write(`${JSON.stringify(value, null, 2)}
`);
}
var root = process.cwd();
var [cmd, ...args] = process.argv.slice(2);
if (cmd === "show") {
  printJson(loadProjectState(root));
  process.exit(0);
}
if (cmd === "detect-mode") {
  printJson(detectDevelopmentMode(root));
  process.exit(0);
}
if (cmd === "set-mode") {
  const mode = args[0];
  if (!MODES2.has(mode)) failUsage();
  printJson(saveProjectState(root, applyDevelopmentMode(loadProjectState(root), mode)));
  process.exit(0);
}
if (cmd === "set-change") {
  const raw = args[0];
  if (!raw) failUsage();
  const id = raw === "null" ? null : raw;
  if (id && !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(id)) {
    console.error("change-id must be kebab-case or null.");
    process.exit(1);
  }
  printJson(saveProjectState(root, applyChangeId(loadProjectState(root), id)));
  process.exit(0);
}
if (cmd === "set-step") {
  const [step, status] = args;
  if (!STEPS2.has(step) || !STATUSES2.has(status)) failUsage();
  try {
    printJson(saveProjectState(root, applyPipelineStep(loadProjectState(root), step, status)));
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  }
  process.exit(0);
}
if (cmd === "set-context") {
  const [slug, step, status] = args;
  if (!slug || !STEPS2.has(step) || !STATUSES2.has(status)) failUsage();
  try {
    printJson(
      saveProjectState(root, applyPipelineContext(loadProjectState(root), slug, step, status))
    );
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  }
  process.exit(0);
}
if (cmd === "check-archive") {
  printJson(checkArchiveReadiness(root, args[0]));
  process.exit(0);
}
if (cmd === "prune-contexts") {
  if (args.length === 0) failUsage();
  printJson(applyPruneContexts(root, args));
  process.exit(0);
}
if (cmd === "archive-done") {
  printJson(saveProjectState(root, applyArchiveComplete(loadProjectState(root))));
  process.exit(0);
}
failUsage();
