#!/usr/bin/env node
/**
 * AUTO-GENERATED by src/kernel/runtime/agent-scripts/bundle-sparrow-promote.mjs — do not edit by hand.
 * Source: src/kernel/runtime/agent-scripts/sparrow-promote.ts (+ src/kernel/runtime/spec-promote.ts).
 * Re-run: npm run sync-schema
 */
// src/kernel/runtime/spec-promote.ts
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync
} from "node:fs";
import { dirname, join, relative } from "node:path";

// src/kernel/runtime/spec-paths.ts
var SPARROW_DOCS = "docs/sparrow";
var SPARROW_DIR = ".sparrow";
var CONFIG_FILE = `${SPARROW_DIR}/sparrow-config.json`;
var LEGACY_CONFIG_FILE = `${SPARROW_DIR}/sparrow.json`;
var STATE_FILE = `${SPARROW_DIR}/sparrow-state.json`;
var LEGACY_ACTIVE_CHANGE_FILE = `${SPARROW_DIR}/active-change.json`;
var MASTER_ROOT = `${SPARROW_DOCS}/master`;
var CHANGE_ROOT = `${SPARROW_DOCS}/change`;
var CHANGE_CURRENT = `${CHANGE_ROOT}/current`;
var CHANGE_ARCHIVE = `${CHANGE_ROOT}/archive`;
var MASTER_PROJECT_MD = `${MASTER_ROOT}/project.md`;
var MASTER_REQUIREMENT_HISTORY = `${MASTER_ROOT}/requirement/revision-history.md`;
var MASTER_DESIGN_HISTORY = `${MASTER_ROOT}/design/revision-history.md`;
var MASTER_BC_HISTORY = `${MASTER_ROOT}/architecture/bc-revision-history.md`;

// src/content/workflows/sparrow-archive/assets/revision-history.md
var revision_history_default = "# \u4FEE\u8BA2\u5386\u53F2\n";

// src/content/workflows/sparrow-archive/assets/revision-history-entry.md
var revision_history_entry_default = "## {changeId}\n\n- **synced-at**: {syncedAt}\n- **source**: {archiveRel}\n\n{deltaGroups}\n";

// src/kernel/runtime/archive-promote-assets.ts
var ASSETS = {
  "revision-history.md": revision_history_default,
  "revision-history-entry.md": revision_history_entry_default
};
function archivePromoteAsset(name) {
  const body = ASSETS[name];
  if (!body) {
    throw new Error(`Missing archive promote asset: ${name}`);
  }
  return body;
}

// src/kernel/runtime/spec-promote.ts
function listFilesRecursive(dir, base = dir) {
  if (!existsSync(dir)) return [];
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      out.push(...listFilesRecursive(full, base));
    } else {
      out.push(relative(base, full).split("\\").join("/"));
    }
  }
  return out;
}
function shouldSkipPromote(rel) {
  const norm = rel.replace(/\\/g, "/");
  if (norm === "proposal.md") return true;
  return /^design\/[^/]+\/plan\.md$/.test(norm);
}
function archiveAsset(name) {
  return archivePromoteAsset(name);
}
function classifyPromoteGroup(rel) {
  const norm = rel.replace(/\\/g, "/");
  const m = /^design\/([^/]+)\//.exec(norm);
  return m ? m[1] : "shared";
}
function normalizeText(text) {
  return text.replace(/\r\n/g, "\n").replace(/\s+$/g, "");
}
function isUnderAllowlist(rel, allowlist) {
  if (!allowlist) return true;
  const group = classifyPromoteGroup(rel);
  if (group === "shared") return true;
  return allowlist.includes(group);
}
function buildModifiedAppend(changeId2, syncedAt2, body) {
  const trimmed = body.replace(/\s+$/g, "");
  return `

---

## Delta \u2014 ${changeId2} (${syncedAt2})

- **kind**: MODIFIED

` + trimmed + `
`;
}
function formatDeltaLines(items) {
  if (items.length === 0) return "- (none)";
  const byKind = { ADDED: [], MODIFIED: [], REMOVED: [] };
  for (const d of items) {
    byKind[d.kind].push(`\`${d.path}\``);
  }
  const lines = [];
  for (const kind of ["ADDED", "MODIFIED", "REMOVED"]) {
    if (byKind[kind].length === 0) continue;
    lines.push(`- ${kind}: ${byKind[kind].join(", ")}`);
  }
  return lines.join("\n") || "- (none)";
}
function buildGroupedHistoryBody(deltas) {
  const groups = /* @__PURE__ */ new Map();
  for (const d of deltas) {
    const list = groups.get(d.slug) ?? [];
    list.push(d);
    groups.set(d.slug, list);
  }
  const keys = [...groups.keys()].sort((a, b) => {
    if (a === "shared") return -1;
    if (b === "shared") return 1;
    return a.localeCompare(b);
  });
  const parts = [];
  for (const key of keys) {
    const heading = key === "shared" ? "### shared" : `### slug: ${key}`;
    parts.push(heading);
    parts.push(formatDeltaLines(groups.get(key) ?? []));
    parts.push("");
  }
  return parts.join("\n").trimEnd();
}
function isRequirementHistoryDelta(d) {
  if (d.path.startsWith("requirement/")) return true;
  return d.slug === "shared" && !d.path.startsWith("architecture/") && !d.path.startsWith("design/") && !d.path.startsWith("requirement/");
}
function isDesignHistoryDelta(d) {
  return d.path.startsWith("architecture/") || d.path.startsWith("design/");
}
function appendHistoryEntry(historyPath, changeId2, syncedAt2, archiveRel, deltas) {
  mkdirSync(dirname(historyPath), { recursive: true });
  const header = existsSync(historyPath) ? readFileSync(historyPath, "utf-8") : archiveAsset("revision-history.md").trimEnd() + "\n\n";
  const grouped = buildGroupedHistoryBody(deltas);
  const entry = archiveAsset("revision-history-entry.md").replaceAll("{changeId}", changeId2).replaceAll("{syncedAt}", syncedAt2).replaceAll("{archiveRel}", archiveRel).replaceAll("{deltaGroups}", grouped).trimEnd();
  writeFileSync(historyPath, header + entry + "\n", "utf-8");
}
function collectSourceRels(folder, allowlist) {
  return listFilesRecursive(folder).map((r) => r.replace(/\\/g, "/")).filter((rel) => !shouldSkipPromote(rel) && isUnderAllowlist(rel, allowlist));
}
function collectMasterRels(projectRoot, allowlist) {
  const master = join(projectRoot, MASTER_ROOT);
  return listFilesRecursive(master).map((r) => r.replace(/\\/g, "/")).filter((rel) => {
    if (rel.endsWith("revision-history.md")) return false;
    if (rel.endsWith("bc-revision-history.md")) return false;
    if (shouldSkipPromote(rel)) return false;
    return isUnderAllowlist(rel, allowlist);
  });
}
function readTextMap(baseDir, rels) {
  const map = {};
  for (const rel of rels) {
    map[rel] = readFileSync(join(baseDir, rel), "utf-8");
  }
  return map;
}
function computeDeltas(sourceTexts, masterTexts, sourceRels, masterRels) {
  const sourceSet = new Set(sourceRels);
  const deltas = [];
  const writePlan = [];
  for (const rel of sourceRels) {
    const srcBody = sourceTexts[rel] ?? "";
    const group = classifyPromoteGroup(rel);
    const masterBody = masterTexts[rel];
    if (masterBody === void 0) {
      deltas.push({ path: rel, kind: "ADDED", slug: group });
      writePlan.push({
        path: rel,
        kind: "ADDED",
        body: srcBody.endsWith("\n") ? srcBody : `${srcBody}
`
      });
      continue;
    }
    if (normalizeText(masterBody) === normalizeText(srcBody)) {
      continue;
    }
    deltas.push({ path: rel, kind: "MODIFIED", slug: group });
    writePlan.push({ path: rel, kind: "MODIFIED", body: srcBody });
  }
  for (const rel of masterRels) {
    if (sourceSet.has(rel)) continue;
    const group = classifyPromoteGroup(rel);
    if (group === "shared") {
      const sourceHasShared = sourceRels.some((r) => classifyPromoteGroup(r) === "shared");
      if (!sourceHasShared) continue;
    } else {
      const sourceHasSlug = sourceRels.some((r) => classifyPromoteGroup(r) === group);
      if (!sourceHasSlug) continue;
    }
    deltas.push({ path: rel, kind: "REMOVED", slug: group });
  }
  return { deltas, writePlan };
}
function applyWritePlan(projectRoot, changeId2, syncedAt2, writePlan) {
  const promotedFiles = [];
  for (const item of writePlan) {
    const dest = join(projectRoot, MASTER_ROOT, item.path);
    if (item.kind === "ADDED") {
      mkdirSync(dirname(dest), { recursive: true });
      writeFileSync(dest, item.body, "utf-8");
    } else {
      const masterBody = readFileSync(dest, "utf-8");
      writeFileSync(
        dest,
        masterBody.replace(/\s+$/g, "") + buildModifiedAppend(changeId2, syncedAt2, item.body),
        "utf-8"
      );
    }
    promotedFiles.push(item.path);
  }
  return promotedFiles;
}
function appendHistories(projectRoot, changeId2, syncedAt2, archiveRel, deltas) {
  const requirementHistoryDeltas = deltas.filter(isRequirementHistoryDelta);
  const designHistoryDeltas = deltas.filter(isDesignHistoryDelta);
  if (requirementHistoryDeltas.length > 0) {
    appendHistoryEntry(
      join(projectRoot, MASTER_REQUIREMENT_HISTORY),
      changeId2,
      syncedAt2,
      archiveRel,
      requirementHistoryDeltas
    );
  }
  if (designHistoryDeltas.length > 0) {
    appendHistoryEntry(
      join(projectRoot, MASTER_DESIGN_HISTORY),
      changeId2,
      syncedAt2,
      archiveRel,
      designHistoryDeltas
    );
  }
  return {
    requirementHistoryAppended: requirementHistoryDeltas.length > 0,
    designHistoryAppended: designHistoryDeltas.length > 0
  };
}
function promoteChangeToMaster(projectRoot, changeId2, syncedAt2, options2 = {}) {
  const source = options2.source ?? "archive";
  const folderName = options2.archiveFolderName ?? `${syncedAt2}-${changeId2}`;
  const folder = source === "current" ? join(projectRoot, CHANGE_CURRENT, changeId2) : join(projectRoot, CHANGE_ARCHIVE, folderName);
  if (!existsSync(folder)) {
    throw new Error(`Change folder not found: ${folder}`);
  }
  const allowlist = options2.slugAllowlist;
  const sourceRels = collectSourceRels(folder, allowlist);
  const masterRels = collectMasterRels(projectRoot, allowlist);
  const sourceTexts = readTextMap(folder, sourceRels);
  const masterTexts = readTextMap(join(projectRoot, MASTER_ROOT), masterRels);
  const { deltas, writePlan } = computeDeltas(sourceTexts, masterTexts, sourceRels, masterRels);
  const promotedFiles = applyWritePlan(projectRoot, changeId2, syncedAt2, writePlan);
  const archiveRel = source === "current" ? `${CHANGE_CURRENT}/${changeId2}/` : `${CHANGE_ARCHIVE}/${folderName}/`;
  const history = appendHistories(projectRoot, changeId2, syncedAt2, archiveRel, deltas);
  return {
    promotedFiles,
    deltas,
    requirementHistoryAppended: history.requirementHistoryAppended,
    designHistoryAppended: history.designHistoryAppended
  };
}

// src/kernel/runtime/agent-scripts/sparrow-promote.ts
function failUsage() {
  console.error("Usage:");
  console.error(
    "  node scripts/sparrow-promote.mjs <change-id> <synced-at> [--source current|archive] [--folder <archiveFolderName>] [--slugs slug1,slug2]"
  );
  process.exit(2);
}
function parseArgs(argv) {
  const positional = [];
  const options2 = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--source") {
      const v = argv[++i];
      if (v !== "current" && v !== "archive") failUsage();
      options2.source = v;
    } else if (a === "--folder") {
      options2.archiveFolderName = argv[++i];
      if (!options2.archiveFolderName) failUsage();
    } else if (a === "--slugs") {
      const raw = argv[++i];
      if (!raw) failUsage();
      options2.slugAllowlist = raw.split(",").map((s) => s.trim()).filter(Boolean);
    } else if (a.startsWith("-")) {
      failUsage();
    } else {
      positional.push(a);
    }
  }
  if (positional.length < 2) failUsage();
  return { changeId: positional[0], syncedAt: positional[1], options: options2 };
}
var { changeId, syncedAt, options } = parseArgs(process.argv.slice(2));
if (!/^\d{4}-\d{2}-\d{2}$/.test(syncedAt)) {
  console.error("synced-at must be YYYY-MM-DD");
  process.exit(1);
}
try {
  const result = promoteChangeToMaster(process.cwd(), changeId, syncedAt, options);
  process.stdout.write(`${JSON.stringify(result, null, 2)}
`);
} catch (err) {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
}
