/** Auto-generated by scripts/sync-bundled-content.mjs — do not edit by hand. */

import specLayoutGuideMd from './templates/shared/spec-layout-guide.md';
export const specLayoutGuide = specLayoutGuideMd;

import _shared_archive_gate_md from './templates/shared/archive-gate.md';
import _shared_assets_project_md from './templates/shared/assets/project.md';
import _shared_grill_me_md from './templates/shared/grill-me.md';
import _shared_output_existence_check_md from './templates/shared/output-existence-check.md';
import _shared_project_md_update_md from './templates/shared/project-md-update.md';
import _shared_revise_gate_md from './templates/shared/revise-gate.md';
import _shared_scripts_sparrow_promote_mjs from './templates/shared/scripts/sparrow-promote.mjs';
import _shared_scripts_sparrow_state_mjs from './templates/shared/scripts/sparrow-state.mjs';
import _shared_spec_layout_guide_md from './templates/shared/spec-layout-guide.md';
import _shared_ubiquitous_language_md from './templates/shared/ubiquitous-language.md';
import _shared_version_metadata_md from './templates/shared/version-metadata.md';

export const sharedReferences: Record<string, string> = {
  'archive-gate.md': _shared_archive_gate_md,
  'grill-me.md': _shared_grill_me_md,
  'output-existence-check.md': _shared_output_existence_check_md,
  'project-md-update.md': _shared_project_md_update_md,
  'revise-gate.md': _shared_revise_gate_md,
  'spec-layout-guide.md': _shared_spec_layout_guide_md,
  'ubiquitous-language.md': _shared_ubiquitous_language_md,
  'version-metadata.md': _shared_version_metadata_md,
};

export const sharedAssets: Record<string, string> = {
  'project.md': _shared_assets_project_md,
};

export const sharedScripts: Record<string, string> = {
  'sparrow-promote.mjs': _shared_scripts_sparrow_promote_mjs,
  'sparrow-state.mjs': _shared_scripts_sparrow_state_mjs,
};

import _skill_sparrow_apply_SKILL_md from './templates/skills/sparrow-apply/SKILL.md';
import _skill_sparrow_apply_assets_code_review_md from './templates/skills/sparrow-apply/assets/code_review.md';
import _skill_sparrow_apply_references_apply_rules_md from './templates/skills/sparrow-apply/references/apply-rules.md';
import _skill_sparrow_apply_references_interaction_apply_md from './templates/skills/sparrow-apply/references/interaction-apply.md';
import _skill_sparrow_arch_SKILL_md from './templates/skills/sparrow-arch/SKILL.md';
import _skill_sparrow_arch_assets_bounded_contexts_md from './templates/skills/sparrow-arch/assets/bounded-contexts.md';
import _skill_sparrow_arch_assets_frontend_md from './templates/skills/sparrow-arch/assets/frontend.md';
import _skill_sparrow_arch_assets_spec_interaction_md from './templates/skills/sparrow-arch/assets/spec-interaction.md';
import _skill_sparrow_arch_assets_spec_md from './templates/skills/sparrow-arch/assets/spec.md';
import _skill_sparrow_arch_references_bc_tiers_md from './templates/skills/sparrow-arch/references/bc-tiers.md';
import _skill_sparrow_arch_references_compat_migrate_md from './templates/skills/sparrow-arch/references/compat-migrate.md';
import _skill_sparrow_arch_references_frontend_architecture_md from './templates/skills/sparrow-arch/references/frontend-architecture.md';
import _skill_sparrow_arch_references_property_rules_md from './templates/skills/sparrow-arch/references/property-rules.md';
import _skill_sparrow_arch_references_react_mapping_md from './templates/skills/sparrow-arch/references/react-mapping.md';
import _skill_sparrow_archive_SKILL_md from './templates/skills/sparrow-archive/SKILL.md';
import _skill_sparrow_archive_assets_bc_revision_history_entry_md from './templates/skills/sparrow-archive/assets/bc-revision-history-entry.md';
import _skill_sparrow_archive_assets_bc_revision_history_md from './templates/skills/sparrow-archive/assets/bc-revision-history.md';
import _skill_sparrow_archive_assets_revision_history_entry_md from './templates/skills/sparrow-archive/assets/revision-history-entry.md';
import _skill_sparrow_archive_assets_revision_history_md from './templates/skills/sparrow-archive/assets/revision-history.md';
import _skill_sparrow_design_SKILL_md from './templates/skills/sparrow-design/SKILL.md';
import _skill_sparrow_design_assets_api_interaction_md from './templates/skills/sparrow-design/assets/api-interaction.md';
import _skill_sparrow_design_assets_api_md from './templates/skills/sparrow-design/assets/api.md';
import _skill_sparrow_design_assets_architecture_api_md from './templates/skills/sparrow-design/assets/architecture-api.md';
import _skill_sparrow_design_assets_tech_interaction_md from './templates/skills/sparrow-design/assets/tech-interaction.md';
import _skill_sparrow_design_assets_tech_md from './templates/skills/sparrow-design/assets/tech.md';
import _skill_sparrow_design_references_api_design_rules_md from './templates/skills/sparrow-design/references/api-design-rules.md';
import _skill_sparrow_design_references_interaction_design_md from './templates/skills/sparrow-design/references/interaction-design.md';
import _skill_sparrow_model_SKILL_md from './templates/skills/sparrow-model/SKILL.md';
import _skill_sparrow_model_assets_model_interaction_md from './templates/skills/sparrow-model/assets/model-interaction.md';
import _skill_sparrow_model_assets_model_md from './templates/skills/sparrow-model/assets/model.md';
import _skill_sparrow_model_references_domain_modeling_steps_md from './templates/skills/sparrow-model/references/domain-modeling-steps.md';
import _skill_sparrow_model_references_view_modeling_md from './templates/skills/sparrow-model/references/view-modeling.md';
import _skill_sparrow_plan_SKILL_md from './templates/skills/sparrow-plan/SKILL.md';
import _skill_sparrow_plan_assets_plan_interaction_md from './templates/skills/sparrow-plan/assets/plan-interaction.md';
import _skill_sparrow_plan_assets_plan_md from './templates/skills/sparrow-plan/assets/plan.md';
import _skill_sparrow_plan_references_interaction_plan_md from './templates/skills/sparrow-plan/references/interaction-plan.md';
import _skill_sparrow_plan_references_module_layouts_md from './templates/skills/sparrow-plan/references/module-layouts.md';
import _skill_sparrow_requirement_SKILL_md from './templates/skills/sparrow-requirement/SKILL.md';
import _skill_sparrow_requirement_assets_capability_md from './templates/skills/sparrow-requirement/assets/capability.md';
import _skill_sparrow_requirement_assets_catalog_md from './templates/skills/sparrow-requirement/assets/catalog.md';
import _skill_sparrow_requirement_assets_component_library_md from './templates/skills/sparrow-requirement/assets/component-library.md';
import _skill_sparrow_requirement_assets_design_tokens_md from './templates/skills/sparrow-requirement/assets/design-tokens.md';
import _skill_sparrow_requirement_assets_prd_business_md from './templates/skills/sparrow-requirement/assets/prd-business.md';
import _skill_sparrow_requirement_assets_prd_quality_md from './templates/skills/sparrow-requirement/assets/prd-quality.md';
import _skill_sparrow_requirement_assets_proposal_md from './templates/skills/sparrow-requirement/assets/proposal.md';
import _skill_sparrow_requirement_assets_prototype_index_html from './templates/skills/sparrow-requirement/assets/prototype-index.html';
import _skill_sparrow_requirement_assets_scenario_md from './templates/skills/sparrow-requirement/assets/scenario.md';
import _skill_sparrow_requirement_assets_service_md from './templates/skills/sparrow-requirement/assets/service.md';
import _skill_sparrow_requirement_assets_subdomain_md from './templates/skills/sparrow-requirement/assets/subdomain.md';
import _skill_sparrow_requirement_assets_ui_spec_md from './templates/skills/sparrow-requirement/assets/ui-spec.md';
import _skill_sparrow_requirement_references_business_service_rules_md from './templates/skills/sparrow-requirement/references/business-service-rules.md';
import _skill_sparrow_requirement_references_compat_migrate_md from './templates/skills/sparrow-requirement/references/compat-migrate.md';
import _skill_sparrow_requirement_references_subdomain_rules_md from './templates/skills/sparrow-requirement/references/subdomain-rules.md';
import _skill_sparrow_requirement_scripts_ensure_change_workspace_mjs from './templates/skills/sparrow-requirement/scripts/ensure-change-workspace.mjs';
import _skill_sparrow_supporting_harness_SKILL_md from './templates/skills/sparrow-supporting-harness/SKILL.md';
import _skill_sparrow_supporting_reconcile_SKILL_md from './templates/skills/sparrow-supporting-reconcile/SKILL.md';
import _skill_sparrow_verify_SKILL_md from './templates/skills/sparrow-verify/SKILL.md';
import _skill_sparrow_verify_assets_verify_report_md from './templates/skills/sparrow-verify/assets/verify_report.md';

export const skillTemplates: Record<string, string> = {
  'sparrow-apply/SKILL.md': _skill_sparrow_apply_SKILL_md,
  'sparrow-arch/SKILL.md': _skill_sparrow_arch_SKILL_md,
  'sparrow-archive/SKILL.md': _skill_sparrow_archive_SKILL_md,
  'sparrow-design/SKILL.md': _skill_sparrow_design_SKILL_md,
  'sparrow-model/SKILL.md': _skill_sparrow_model_SKILL_md,
  'sparrow-plan/SKILL.md': _skill_sparrow_plan_SKILL_md,
  'sparrow-requirement/SKILL.md': _skill_sparrow_requirement_SKILL_md,
  'sparrow-supporting-harness/SKILL.md': _skill_sparrow_supporting_harness_SKILL_md,
  'sparrow-supporting-reconcile/SKILL.md': _skill_sparrow_supporting_reconcile_SKILL_md,
  'sparrow-verify/SKILL.md': _skill_sparrow_verify_SKILL_md,
};

export const skillExtras: Record<string, Record<string, string>> = {
  'sparrow-apply': {
    'assets/code_review.md': _skill_sparrow_apply_assets_code_review_md,
    'references/apply-rules.md': _skill_sparrow_apply_references_apply_rules_md,
    'references/interaction-apply.md': _skill_sparrow_apply_references_interaction_apply_md,
  },
  'sparrow-arch': {
    'assets/bounded-contexts.md': _skill_sparrow_arch_assets_bounded_contexts_md,
    'assets/frontend.md': _skill_sparrow_arch_assets_frontend_md,
    'assets/spec-interaction.md': _skill_sparrow_arch_assets_spec_interaction_md,
    'assets/spec.md': _skill_sparrow_arch_assets_spec_md,
    'references/bc-tiers.md': _skill_sparrow_arch_references_bc_tiers_md,
    'references/compat-migrate.md': _skill_sparrow_arch_references_compat_migrate_md,
    'references/frontend-architecture.md': _skill_sparrow_arch_references_frontend_architecture_md,
    'references/property-rules.md': _skill_sparrow_arch_references_property_rules_md,
    'references/react-mapping.md': _skill_sparrow_arch_references_react_mapping_md,
  },
  'sparrow-archive': {
    'assets/bc-revision-history-entry.md': _skill_sparrow_archive_assets_bc_revision_history_entry_md,
    'assets/bc-revision-history.md': _skill_sparrow_archive_assets_bc_revision_history_md,
    'assets/revision-history-entry.md': _skill_sparrow_archive_assets_revision_history_entry_md,
    'assets/revision-history.md': _skill_sparrow_archive_assets_revision_history_md,
  },
  'sparrow-design': {
    'assets/api-interaction.md': _skill_sparrow_design_assets_api_interaction_md,
    'assets/api.md': _skill_sparrow_design_assets_api_md,
    'assets/architecture-api.md': _skill_sparrow_design_assets_architecture_api_md,
    'assets/tech-interaction.md': _skill_sparrow_design_assets_tech_interaction_md,
    'assets/tech.md': _skill_sparrow_design_assets_tech_md,
    'references/api-design-rules.md': _skill_sparrow_design_references_api_design_rules_md,
    'references/interaction-design.md': _skill_sparrow_design_references_interaction_design_md,
  },
  'sparrow-model': {
    'assets/model-interaction.md': _skill_sparrow_model_assets_model_interaction_md,
    'assets/model.md': _skill_sparrow_model_assets_model_md,
    'references/domain-modeling-steps.md': _skill_sparrow_model_references_domain_modeling_steps_md,
    'references/view-modeling.md': _skill_sparrow_model_references_view_modeling_md,
  },
  'sparrow-plan': {
    'assets/plan-interaction.md': _skill_sparrow_plan_assets_plan_interaction_md,
    'assets/plan.md': _skill_sparrow_plan_assets_plan_md,
    'references/interaction-plan.md': _skill_sparrow_plan_references_interaction_plan_md,
    'references/module-layouts.md': _skill_sparrow_plan_references_module_layouts_md,
  },
  'sparrow-requirement': {
    'assets/capability.md': _skill_sparrow_requirement_assets_capability_md,
    'assets/catalog.md': _skill_sparrow_requirement_assets_catalog_md,
    'assets/component-library.md': _skill_sparrow_requirement_assets_component_library_md,
    'assets/design-tokens.md': _skill_sparrow_requirement_assets_design_tokens_md,
    'assets/prd-business.md': _skill_sparrow_requirement_assets_prd_business_md,
    'assets/prd-quality.md': _skill_sparrow_requirement_assets_prd_quality_md,
    'assets/proposal.md': _skill_sparrow_requirement_assets_proposal_md,
    'assets/prototype-index.html': _skill_sparrow_requirement_assets_prototype_index_html,
    'assets/scenario.md': _skill_sparrow_requirement_assets_scenario_md,
    'assets/service.md': _skill_sparrow_requirement_assets_service_md,
    'assets/subdomain.md': _skill_sparrow_requirement_assets_subdomain_md,
    'assets/ui-spec.md': _skill_sparrow_requirement_assets_ui_spec_md,
    'references/business-service-rules.md': _skill_sparrow_requirement_references_business_service_rules_md,
    'references/compat-migrate.md': _skill_sparrow_requirement_references_compat_migrate_md,
    'references/subdomain-rules.md': _skill_sparrow_requirement_references_subdomain_rules_md,
    'scripts/ensure-change-workspace.mjs': _skill_sparrow_requirement_scripts_ensure_change_workspace_mjs,
  },
  'sparrow-supporting-harness': {
  },
  'sparrow-supporting-reconcile': {
  },
  'sparrow-verify': {
    'assets/verify_report.md': _skill_sparrow_verify_assets_verify_report_md,
  },
};

import _wf_sparrow_apply_md from './workflow-blocks/sparrow-apply.md';
import _wf_sparrow_arch_md from './workflow-blocks/sparrow-arch.md';
import _wf_sparrow_archive_md from './workflow-blocks/sparrow-archive.md';
import _wf_sparrow_design_md from './workflow-blocks/sparrow-design.md';
import _wf_sparrow_model_md from './workflow-blocks/sparrow-model.md';
import _wf_sparrow_plan_md from './workflow-blocks/sparrow-plan.md';
import _wf_sparrow_requirement_md from './workflow-blocks/sparrow-requirement.md';
import _wf_sparrow_verify_md from './workflow-blocks/sparrow-verify.md';

export const workflowBlocks: Record<string, string> = {
  'sparrow-apply.md': _wf_sparrow_apply_md,
  'sparrow-arch.md': _wf_sparrow_arch_md,
  'sparrow-archive.md': _wf_sparrow_archive_md,
  'sparrow-design.md': _wf_sparrow_design_md,
  'sparrow-model.md': _wf_sparrow_model_md,
  'sparrow-plan.md': _wf_sparrow_plan_md,
  'sparrow-requirement.md': _wf_sparrow_requirement_md,
  'sparrow-verify.md': _wf_sparrow_verify_md,
};

import _h_apply_implementation_md from './templates/harness/apply/implementation.md';
import _h_arch_bounded_contexts_md from './templates/harness/arch/bounded-contexts.md';
import _h_arch_frontend_md from './templates/harness/arch/frontend.md';
import _h_arch_spec_slice_md from './templates/harness/arch/spec-slice.md';
import _h_common_README_md from './templates/harness/common/README.md';
import _h_common_always_interactive_interaction_md from './templates/harness/common/always/interactive-interaction.md';
import _h_common_conditional_brownfield_md from './templates/harness/common/conditional/brownfield.md';
import _h_constitution_md from './templates/harness/constitution.md';
import _h_design_api_design_md from './templates/harness/design/api-design.md';
import _h_model_architecture_md from './templates/harness/model/architecture.md';
import _h_model_domain_modeling_md from './templates/harness/model/domain-modeling.md';
import _h_model_view_modeling_md from './templates/harness/model/view-modeling.md';
import _h_requirement_requirements_md from './templates/harness/requirement/requirements.md';
import _h_requirement_subdomains_md from './templates/harness/requirement/subdomains.md';

export interface BundledHarnessEntry { relPath: string; title: string; body: string; }

export const bundledHarnessBodies: Record<string, { title: string; body: string }> = {
  'apply/implementation.md': { title: "代码实现约束（apply / implementation）", body: _h_apply_implementation_md },
  'arch/bounded-contexts.md': { title: "限界上下文约束（arch / bounded-contexts）", body: _h_arch_bounded_contexts_md },
  'arch/frontend.md': { title: "前端架构约束（arch / frontend）", body: _h_arch_frontend_md },
  'arch/spec-slice.md': { title: "规格切片约束（arch / spec-slice）", body: _h_arch_spec_slice_md },
  'common/README.md': { title: "通用约束（common）", body: _h_common_README_md },
  'common/always/interactive-interaction.md': { title: "互动式交互纪律（interactive-interaction）", body: _h_common_always_interactive_interaction_md },
  'common/conditional/brownfield.md': { title: "棕地项目约束（brownfield）", body: _h_common_conditional_brownfield_md },
  'constitution.md': { title: "Sparrow 约束资产宪法（Harness Constitution）", body: _h_constitution_md },
  'design/api-design.md': { title: "API 设计约束（design / api-design）", body: _h_design_api_design_md },
  'model/architecture.md': { title: "领域建模架构约束（model / architecture）", body: _h_model_architecture_md },
  'model/domain-modeling.md': { title: "领域建模约束（model / domain-modeling）", body: _h_model_domain_modeling_md },
  'model/view-modeling.md': { title: "View Model 建模约束（model / view-modeling）", body: _h_model_view_modeling_md },
  'requirement/requirements.md': { title: "需求约束（requirement / requirements）", body: _h_requirement_requirements_md },
  'requirement/subdomains.md': { title: "子领域约束（requirement / subdomains）", body: _h_requirement_subdomains_md },
};

