/** Auto-generated by src/content/sync/sync-bundled-content.mjs — do not edit by hand. */

import specLayoutGuideMd from './workflows/_shared/spec-layout-guide.md';
export const specLayoutGuide = specLayoutGuideMd;

import _shared_archive_gate_md from './workflows/_shared/archive-gate.md';
import _shared_assets_project_md from './workflows/_shared/assets/project.md';
import _shared_grill_me_md from './workflows/_shared/grill-me.md';
import _shared_output_existence_check_md from './workflows/_shared/output-existence-check.md';
import _shared_project_md_update_md from './workflows/_shared/project-md-update.md';
import _shared_revise_gate_md from './workflows/_shared/revise-gate.md';
import _shared_scripts_sparrow_promote_mjs from './workflows/_shared/scripts/sparrow-promote.mjs';
import _shared_scripts_sparrow_state_mjs from './workflows/_shared/scripts/sparrow-state.mjs';
import _shared_spec_layout_guide_md from './workflows/_shared/spec-layout-guide.md';
import _shared_ubiquitous_language_md from './workflows/_shared/ubiquitous-language.md';
import _shared_version_metadata_md from './workflows/_shared/version-metadata.md';

export const sharedReferences: Record<string, string> = {
  'archive-gate.md': _shared_archive_gate_md,
  'grill-me.md': _shared_grill_me_md,
  'output-existence-check.md': _shared_output_existence_check_md,
  'project-md-update.md': _shared_project_md_update_md,
  'revise-gate.md': _shared_revise_gate_md,
  'spec-layout-guide.md': _shared_spec_layout_guide_md,
  'ubiquitous-language.md': _shared_ubiquitous_language_md,
  'version-metadata.md': _shared_version_metadata_md,
};

export const sharedAssets: Record<string, string> = {
  'project.md': _shared_assets_project_md,
};

export const sharedScripts: Record<string, string> = {
  'sparrow-promote.mjs': _shared_scripts_sparrow_promote_mjs,
  'sparrow-state.mjs': _shared_scripts_sparrow_state_mjs,
};

import _wf_sparrow_apply_activity_md from './workflows/sparrow-apply/activity.md';
import _wf_sparrow_apply_assets_code_review_md from './workflows/sparrow-apply/assets/code_review.md';
import _wf_sparrow_apply_checkpoint_md from './workflows/sparrow-apply/checkpoint.md';
import _wf_sparrow_apply_guideline_md from './workflows/sparrow-apply/guideline.md';
import _wf_sparrow_apply_references_apply_rules_md from './workflows/sparrow-apply/references/apply-rules.md';
import _wf_sparrow_apply_references_interaction_apply_md from './workflows/sparrow-apply/references/interaction-apply.md';
import _wf_sparrow_architecture_activity_md from './workflows/sparrow-architecture/activity.md';
import _wf_sparrow_architecture_assets_bounded_contexts_md from './workflows/sparrow-architecture/assets/bounded-contexts.md';
import _wf_sparrow_architecture_assets_frontend_md from './workflows/sparrow-architecture/assets/frontend.md';
import _wf_sparrow_architecture_assets_spec_interaction_md from './workflows/sparrow-architecture/assets/spec-interaction.md';
import _wf_sparrow_architecture_assets_spec_md from './workflows/sparrow-architecture/assets/spec.md';
import _wf_sparrow_architecture_checkpoint_md from './workflows/sparrow-architecture/checkpoint.md';
import _wf_sparrow_architecture_guideline_md from './workflows/sparrow-architecture/guideline.md';
import _wf_sparrow_architecture_references_bc_tiers_md from './workflows/sparrow-architecture/references/bc-tiers.md';
import _wf_sparrow_architecture_references_compat_migrate_md from './workflows/sparrow-architecture/references/compat-migrate.md';
import _wf_sparrow_architecture_references_frontend_architecture_md from './workflows/sparrow-architecture/references/frontend-architecture.md';
import _wf_sparrow_architecture_references_property_rules_md from './workflows/sparrow-architecture/references/property-rules.md';
import _wf_sparrow_architecture_references_react_mapping_md from './workflows/sparrow-architecture/references/react-mapping.md';
import _wf_sparrow_archive_activity_md from './workflows/sparrow-archive/activity.md';
import _wf_sparrow_archive_assets_bc_revision_history_entry_md from './workflows/sparrow-archive/assets/bc-revision-history-entry.md';
import _wf_sparrow_archive_assets_bc_revision_history_md from './workflows/sparrow-archive/assets/bc-revision-history.md';
import _wf_sparrow_archive_assets_revision_history_entry_md from './workflows/sparrow-archive/assets/revision-history-entry.md';
import _wf_sparrow_archive_assets_revision_history_md from './workflows/sparrow-archive/assets/revision-history.md';
import _wf_sparrow_archive_checkpoint_md from './workflows/sparrow-archive/checkpoint.md';
import _wf_sparrow_archive_guideline_md from './workflows/sparrow-archive/guideline.md';
import _wf_sparrow_design_activity_md from './workflows/sparrow-design/activity.md';
import _wf_sparrow_design_assets_api_interaction_md from './workflows/sparrow-design/assets/api-interaction.md';
import _wf_sparrow_design_assets_api_md from './workflows/sparrow-design/assets/api.md';
import _wf_sparrow_design_assets_architecture_api_md from './workflows/sparrow-design/assets/architecture-api.md';
import _wf_sparrow_design_assets_tech_interaction_md from './workflows/sparrow-design/assets/tech-interaction.md';
import _wf_sparrow_design_assets_tech_md from './workflows/sparrow-design/assets/tech.md';
import _wf_sparrow_design_checkpoint_md from './workflows/sparrow-design/checkpoint.md';
import _wf_sparrow_design_guideline_md from './workflows/sparrow-design/guideline.md';
import _wf_sparrow_design_references_api_design_rules_md from './workflows/sparrow-design/references/api-design-rules.md';
import _wf_sparrow_design_references_interaction_design_md from './workflows/sparrow-design/references/interaction-design.md';
import _wf_sparrow_model_activity_md from './workflows/sparrow-model/activity.md';
import _wf_sparrow_model_assets_model_interaction_md from './workflows/sparrow-model/assets/model-interaction.md';
import _wf_sparrow_model_assets_model_md from './workflows/sparrow-model/assets/model.md';
import _wf_sparrow_model_checkpoint_md from './workflows/sparrow-model/checkpoint.md';
import _wf_sparrow_model_guideline_md from './workflows/sparrow-model/guideline.md';
import _wf_sparrow_model_references_domain_modeling_steps_md from './workflows/sparrow-model/references/domain-modeling-steps.md';
import _wf_sparrow_model_references_view_modeling_md from './workflows/sparrow-model/references/view-modeling.md';
import _wf_sparrow_plan_activity_md from './workflows/sparrow-plan/activity.md';
import _wf_sparrow_plan_assets_plan_interaction_md from './workflows/sparrow-plan/assets/plan-interaction.md';
import _wf_sparrow_plan_assets_plan_md from './workflows/sparrow-plan/assets/plan.md';
import _wf_sparrow_plan_checkpoint_md from './workflows/sparrow-plan/checkpoint.md';
import _wf_sparrow_plan_guideline_md from './workflows/sparrow-plan/guideline.md';
import _wf_sparrow_plan_references_interaction_plan_md from './workflows/sparrow-plan/references/interaction-plan.md';
import _wf_sparrow_plan_references_module_layouts_md from './workflows/sparrow-plan/references/module-layouts.md';
import _wf_sparrow_requirement_activity_md from './workflows/sparrow-requirement/activity.md';
import _wf_sparrow_requirement_assets_business_services_md from './workflows/sparrow-requirement/assets/business-services.md';
import _wf_sparrow_requirement_assets_capability_md from './workflows/sparrow-requirement/assets/capability.md';
import _wf_sparrow_requirement_assets_catalog_md from './workflows/sparrow-requirement/assets/catalog.md';
import _wf_sparrow_requirement_assets_component_library_md from './workflows/sparrow-requirement/assets/component-library.md';
import _wf_sparrow_requirement_assets_design_tokens_md from './workflows/sparrow-requirement/assets/design-tokens.md';
import _wf_sparrow_requirement_assets_proposal_md from './workflows/sparrow-requirement/assets/proposal.md';
import _wf_sparrow_requirement_assets_prototype_index_html from './workflows/sparrow-requirement/assets/prototype-index.html';
import _wf_sparrow_requirement_assets_quality_md from './workflows/sparrow-requirement/assets/quality.md';
import _wf_sparrow_requirement_assets_scenario_md from './workflows/sparrow-requirement/assets/scenario.md';
import _wf_sparrow_requirement_assets_service_md from './workflows/sparrow-requirement/assets/service.md';
import _wf_sparrow_requirement_assets_subdomain_md from './workflows/sparrow-requirement/assets/subdomain.md';
import _wf_sparrow_requirement_assets_ui_spec_md from './workflows/sparrow-requirement/assets/ui-spec.md';
import _wf_sparrow_requirement_checkpoint_md from './workflows/sparrow-requirement/checkpoint.md';
import _wf_sparrow_requirement_guideline_md from './workflows/sparrow-requirement/guideline.md';
import _wf_sparrow_requirement_references_business_service_rules_md from './workflows/sparrow-requirement/references/business-service-rules.md';
import _wf_sparrow_requirement_references_compat_migrate_md from './workflows/sparrow-requirement/references/compat-migrate.md';
import _wf_sparrow_requirement_references_subdomain_rules_md from './workflows/sparrow-requirement/references/subdomain-rules.md';
import _wf_sparrow_requirement_scripts_ensure_change_workspace_mjs from './workflows/sparrow-requirement/scripts/ensure-change-workspace.mjs';
import _wf_sparrow_supporting_harness_activity_md from './workflows/sparrow-supporting-harness/activity.md';
import _wf_sparrow_supporting_reconcile_activity_md from './workflows/sparrow-supporting-reconcile/activity.md';
import _wf_sparrow_verify_activity_md from './workflows/sparrow-verify/activity.md';
import _wf_sparrow_verify_assets_verify_report_md from './workflows/sparrow-verify/assets/verify_report.md';
import _wf_sparrow_verify_guideline_md from './workflows/sparrow-verify/guideline.md';

export const skillTemplates: Record<string, string> = {
  'sparrow-apply/SKILL.md': _wf_sparrow_apply_activity_md,
  'sparrow-architecture/SKILL.md': _wf_sparrow_architecture_activity_md,
  'sparrow-archive/SKILL.md': _wf_sparrow_archive_activity_md,
  'sparrow-design/SKILL.md': _wf_sparrow_design_activity_md,
  'sparrow-model/SKILL.md': _wf_sparrow_model_activity_md,
  'sparrow-plan/SKILL.md': _wf_sparrow_plan_activity_md,
  'sparrow-requirement/SKILL.md': _wf_sparrow_requirement_activity_md,
  'sparrow-supporting-harness/SKILL.md': _wf_sparrow_supporting_harness_activity_md,
  'sparrow-supporting-reconcile/SKILL.md': _wf_sparrow_supporting_reconcile_activity_md,
  'sparrow-verify/SKILL.md': _wf_sparrow_verify_activity_md,
};

export const skillExtras: Record<string, Record<string, string>> = {
  'sparrow-apply': {
    'assets/code_review.md': _wf_sparrow_apply_assets_code_review_md,
    'checkpoint.md': _wf_sparrow_apply_checkpoint_md,
    'references/apply-rules.md': _wf_sparrow_apply_references_apply_rules_md,
    'references/interaction-apply.md': _wf_sparrow_apply_references_interaction_apply_md,
  },
  'sparrow-architecture': {
    'assets/bounded-contexts.md': _wf_sparrow_architecture_assets_bounded_contexts_md,
    'assets/frontend.md': _wf_sparrow_architecture_assets_frontend_md,
    'assets/spec-interaction.md': _wf_sparrow_architecture_assets_spec_interaction_md,
    'assets/spec.md': _wf_sparrow_architecture_assets_spec_md,
    'checkpoint.md': _wf_sparrow_architecture_checkpoint_md,
    'references/bc-tiers.md': _wf_sparrow_architecture_references_bc_tiers_md,
    'references/compat-migrate.md': _wf_sparrow_architecture_references_compat_migrate_md,
    'references/frontend-architecture.md': _wf_sparrow_architecture_references_frontend_architecture_md,
    'references/property-rules.md': _wf_sparrow_architecture_references_property_rules_md,
    'references/react-mapping.md': _wf_sparrow_architecture_references_react_mapping_md,
  },
  'sparrow-archive': {
    'assets/bc-revision-history-entry.md': _wf_sparrow_archive_assets_bc_revision_history_entry_md,
    'assets/bc-revision-history.md': _wf_sparrow_archive_assets_bc_revision_history_md,
    'assets/revision-history-entry.md': _wf_sparrow_archive_assets_revision_history_entry_md,
    'assets/revision-history.md': _wf_sparrow_archive_assets_revision_history_md,
    'checkpoint.md': _wf_sparrow_archive_checkpoint_md,
  },
  'sparrow-design': {
    'assets/api-interaction.md': _wf_sparrow_design_assets_api_interaction_md,
    'assets/api.md': _wf_sparrow_design_assets_api_md,
    'assets/architecture-api.md': _wf_sparrow_design_assets_architecture_api_md,
    'assets/tech-interaction.md': _wf_sparrow_design_assets_tech_interaction_md,
    'assets/tech.md': _wf_sparrow_design_assets_tech_md,
    'checkpoint.md': _wf_sparrow_design_checkpoint_md,
    'references/api-design-rules.md': _wf_sparrow_design_references_api_design_rules_md,
    'references/interaction-design.md': _wf_sparrow_design_references_interaction_design_md,
  },
  'sparrow-model': {
    'assets/model-interaction.md': _wf_sparrow_model_assets_model_interaction_md,
    'assets/model.md': _wf_sparrow_model_assets_model_md,
    'checkpoint.md': _wf_sparrow_model_checkpoint_md,
    'references/domain-modeling-steps.md': _wf_sparrow_model_references_domain_modeling_steps_md,
    'references/view-modeling.md': _wf_sparrow_model_references_view_modeling_md,
  },
  'sparrow-plan': {
    'assets/plan-interaction.md': _wf_sparrow_plan_assets_plan_interaction_md,
    'assets/plan.md': _wf_sparrow_plan_assets_plan_md,
    'checkpoint.md': _wf_sparrow_plan_checkpoint_md,
    'references/interaction-plan.md': _wf_sparrow_plan_references_interaction_plan_md,
    'references/module-layouts.md': _wf_sparrow_plan_references_module_layouts_md,
  },
  'sparrow-requirement': {
    'assets/business-services.md': _wf_sparrow_requirement_assets_business_services_md,
    'assets/capability.md': _wf_sparrow_requirement_assets_capability_md,
    'assets/catalog.md': _wf_sparrow_requirement_assets_catalog_md,
    'assets/component-library.md': _wf_sparrow_requirement_assets_component_library_md,
    'assets/design-tokens.md': _wf_sparrow_requirement_assets_design_tokens_md,
    'assets/proposal.md': _wf_sparrow_requirement_assets_proposal_md,
    'assets/prototype-index.html': _wf_sparrow_requirement_assets_prototype_index_html,
    'assets/quality.md': _wf_sparrow_requirement_assets_quality_md,
    'assets/scenario.md': _wf_sparrow_requirement_assets_scenario_md,
    'assets/service.md': _wf_sparrow_requirement_assets_service_md,
    'assets/subdomain.md': _wf_sparrow_requirement_assets_subdomain_md,
    'assets/ui-spec.md': _wf_sparrow_requirement_assets_ui_spec_md,
    'checkpoint.md': _wf_sparrow_requirement_checkpoint_md,
    'references/business-service-rules.md': _wf_sparrow_requirement_references_business_service_rules_md,
    'references/compat-migrate.md': _wf_sparrow_requirement_references_compat_migrate_md,
    'references/subdomain-rules.md': _wf_sparrow_requirement_references_subdomain_rules_md,
    'scripts/ensure-change-workspace.mjs': _wf_sparrow_requirement_scripts_ensure_change_workspace_mjs,
  },
  'sparrow-supporting-harness': {
  },
  'sparrow-supporting-reconcile': {
  },
  'sparrow-verify': {
    'assets/verify_report.md': _wf_sparrow_verify_assets_verify_report_md,
  },
};

export const workflowBlocks: Record<string, string> = {
  'sparrow-apply.md': _wf_sparrow_apply_guideline_md,
  'sparrow-architecture.md': _wf_sparrow_architecture_guideline_md,
  'sparrow-archive.md': _wf_sparrow_archive_guideline_md,
  'sparrow-design.md': _wf_sparrow_design_guideline_md,
  'sparrow-model.md': _wf_sparrow_model_guideline_md,
  'sparrow-plan.md': _wf_sparrow_plan_guideline_md,
  'sparrow-requirement.md': _wf_sparrow_requirement_guideline_md,
  'sparrow-verify.md': _wf_sparrow_verify_guideline_md,
};

import _h_apply_implementation_md from './harness/apply/implementation.md';
import _h_arch_bounded_contexts_md from './harness/arch/bounded-contexts.md';
import _h_arch_frontend_md from './harness/arch/frontend.md';
import _h_arch_spec_slice_md from './harness/arch/spec-slice.md';
import _h_common_README_md from './harness/common/README.md';
import _h_common_always_document_language_md from './harness/common/always/document-language.md';
import _h_common_always_interactive_interaction_md from './harness/common/always/interactive-interaction.md';
import _h_common_conditional_brownfield_md from './harness/common/conditional/brownfield.md';
import _h_constitution_md from './harness/constitution.md';
import _h_design_api_design_md from './harness/design/api-design.md';
import _h_model_architecture_md from './harness/model/architecture.md';
import _h_model_domain_modeling_md from './harness/model/domain-modeling.md';
import _h_model_view_modeling_md from './harness/model/view-modeling.md';
import _h_requirement_ingest_cli_md from './harness/requirement/ingest-cli.md';
import _h_requirement_requirements_md from './harness/requirement/requirements.md';
import _h_requirement_subdomains_md from './harness/requirement/subdomains.md';

export interface BundledHarnessEntry { relPath: string; title: string; body: string; }

export const bundledHarnessBodies: Record<string, { title: string; body: string }> = {
  'apply/implementation.md': { title: "代码实现约束（apply / implementation）", body: _h_apply_implementation_md },
  'arch/bounded-contexts.md': { title: "限界上下文约束（arch / bounded-contexts）", body: _h_arch_bounded_contexts_md },
  'arch/frontend.md': { title: "前端架构约束（arch / frontend）", body: _h_arch_frontend_md },
  'arch/spec-slice.md': { title: "规格切片约束（arch / spec-slice）", body: _h_arch_spec_slice_md },
  'common/README.md': { title: "通用约束（common）", body: _h_common_README_md },
  'common/always/document-language.md': { title: "文档语言（common / always / document-language）", body: _h_common_always_document_language_md },
  'common/always/interactive-interaction.md': { title: "互动式交互纪律（interactive-interaction）", body: _h_common_always_interactive_interaction_md },
  'common/conditional/brownfield.md': { title: "棕地项目约束（brownfield）", body: _h_common_conditional_brownfield_md },
  'constitution.md': { title: "Sparrow 约束资产宪法（Harness Constitution）", body: _h_constitution_md },
  'design/api-design.md': { title: "API 设计约束（design / api-design）", body: _h_design_api_design_md },
  'model/architecture.md': { title: "领域建模架构约束（model / architecture）", body: _h_model_architecture_md },
  'model/domain-modeling.md': { title: "领域建模约束（model / domain-modeling）", body: _h_model_domain_modeling_md },
  'model/view-modeling.md': { title: "View Model 建模约束（model / view-modeling）", body: _h_model_view_modeling_md },
  'requirement/ingest-cli.md': { title: "原始需求文档 ingest（requirement）", body: _h_requirement_ingest_cli_md },
  'requirement/requirements.md': { title: "需求约束（requirement / requirements）", body: _h_requirement_requirements_md },
  'requirement/subdomains.md': { title: "子领域约束（requirement / subdomains）", body: _h_requirement_subdomains_md },
};

